### ISSUE TITLE
A couple of problems with the current timeout

### ISSUE THREAD

**Issue by joel-magnusson** [AlbinJS/IPTClock#26]
1. The timeout timer is ticking down at an incorrect pace (I've timed it). You most likely need to take the computational time into account!

2. If you press 'timeout' and then 'next', you will not be able to start the clock again. 'reset' doesn't seem to help either.

**Comment by AlbinJS** [comment]
It works for me, can you be more precise?
Did you let the timeout finish or push "dismiss" before trying to continue?

**Comment by joel-magnusson** [comment]
Hmm.. that problem doesn't seem to occur anymore. 

However, the clock is still not ticking down correctly. Do fix this or it will practically be unusable (change refresh rate if necessary).

**Comment by AlbinJS** [comment]
This issue should now be dealt with, so I'm closing it.

**Comment by joel-magnusson** [comment]
I get the following message when running the timer:
```
Starting
String: 00:06:00
String: 00:06:90
String: 00:06:80
String: 00:06:70
String: 00:06:60
String: 00:06:50
String: 00:06:40
String: 00:06:30
String: 00:06:20
String: 00:06:10
String: 00:05:00
String: 00:05:90
String: 00:05:80
String: 00:05:70
String: 00:05:60
String: 00:05:50
String: 00:05:40
String: 00:05:30
String: 00:05:20
String: 00:05:10
String: 00:04:00
String: 00:04:90
String: 00:04:80
String: 00:04:70
String: 00:04:60
String: 00:04:50
String: 00:04:40
String: 00:04:30
String: 00:04:20
String: 00:04:10
String: 00:03:00
String: 00:03:90
String: 00:03:80
String: 00:03:70
String: 00:03:60
String: 00:03:50
String: 00:03:40
String: 00:03:30
String: 00:03:20
String: 00:03:10
String: 00:02:00
String: 00:02:90
String: 00:02:80
String: 00:02:70
String: 00:02:60
String: 00:02:50
String: 00:02:40
String: 00:02:30
String: 00:02:20
String: 00:02:10
String: 00:01:00
String: 00:01:90
String: 00:01:80
String: 00:01:70
String: 00:01:60
String: 00:01:50
String: 00:01:40
String: 00:01:30
String: 00:01:20
String: 00:01:10
String: 00:00:00
String: -00:00:10
Exception in Tkinter callback
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/tkinter/__init__.py", line 1550, in __call__
    return self.func(*args)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/tkinter/__init__.py", line 596, in callit
    func(*args)
  File "/Users/joel/Coding/IPTClock/Classes/iptclock_classes.py", line 501, in update
    self.msg.configure(text=self.timer.string())
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/tkinter/__init__.py", line 1330, in configure
    return self._configure('configure', cnf, kw)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/tkinter/__init__.py", line 1321, in _configure
    self.tk.call(_flatten((self._w, cmd)) + self._options(cnf))
_tkinter.TclError: invalid command name ".4466209344.4466209288"
```

Furthermore, just to be sure, does the timeout countdown take the actual computational time into account?
